// src/Outfit.js
const outfits = [
    // Men's Outfits
    {
        id:1,
        category: 'Beauty',
        productName: 'Liquid LIp color',
        ratings: 4.7,
        price:120,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRFRvX1jHMVWsTmil2JhieOn563MMMUzDz_oBl251IrzOwvhiCl-QwtBcq2iwx3PnbZUfpDtrH5CsVGhxBt1nPM1wuaU2OqccIPKgUsWMIPaTX9oON3uHdNAQ&usqp=CAE',
    },
    {
        id:2,
        category: 'Home & Living',
        productName: 'Hem Leaf',
        ratings: 4.7,
        price:130,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTS-iGqnBARn0-k7pNKrHVgEVoh7fDsuU_xTlzDB5kf0zIBnVxocsW78EGEhFMVj_HYlJ8moTkTifHhhg8YAL_Zbvoq_CXBqmvwtQyQtzS2&usqp=CAE',
    },
    {
        id:3,
        category: 'Men',
        productName: 'Shirts',
        ratings: 4.7,
        price:100,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTklezuOoTOT20UcHVsTH9Cijv1i-cllqI6IxpQmNXr1GAxrVVO_7WWO8LYffQbjhbarZwUs0lxEa_-hwXpBc4zWsf8rAvErWDyJMf1liRadWzl5QnL2Y9GeA&usqp=CAE',
    },
    { 
        id:4,
        category: 'Kids',
        productName: 'Jackets',
        ratings: 4.7,
        price:200,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRD3wy3f8LpBAJBquShxiNLLW3Zs5k31hxp-FvIvGGttCbhRtfyVWZ-0fiSb-AI39QR4USC9WLNkWriCphVJ6drhYPbK8xMGH3gxfHqSbqG7xbCK952uHg5vA&usqp=CAE',
    },
    {
        id:5,
        category: 'Beauty',
        productName: 'Matte Lip Stick',
        ratings: 4.7,
        price:250,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQhXWqe16h3nrorK_5zsWyIkV9naJm9exz0ROJP-P_9FGk0jcYguxxUGJ5hlobsjLwb_32hV87SSuf7PsoRqdA_YR24lGR6td3Z58FjSdhOOhb_boP_nSgM&usqp=CAE',
    },
    {
        id:6,
        category: 'Women',
        productName: 'Crop top',
        ratings: 4.8,
        price:100,
        discountPrice: 59.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSPDjBbIA5DjmWxxva72NENfAoD2DEbCwyY95kMMgUMUN79bDzG2nCSOUvFHosBfz9aJPf0_ZX2BwvX7NmCwGRp0AdKKTSDrjpdp280cDIv&usqp=CAE',
    },
    {
        id:7,
        category: 'Home & Living',
        productName: 'Terracote Vase',
        ratings: 4.7,
        price:70,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTsY-iVd9ec3GiGrRthcQSKRm_oeiUy-h89nla9ZGqoZDNC7McPS22h1WtNuMzdl-IMsiI1f02PKvF28nD8gUl-F_zxf8hy1UbpzIN3Byc&usqp=CAE',
    },
    {
        id:8,
        category: 'Men',
        productName: 'T shirts',
        ratings: 4.7,
        price:180,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTSGtHYectmWkv8zKBcpxjm8RuJpJrBYbtpcc-VTSvCytrlo5kPUb6ITx4V1h_UAwTOo2sycWASfu_uY08c_Iow2oIhfPbjiUuPSsiLMaA&usqp=CAE',
    },
    {
        id:9,
        category: 'Beauty',
        productName: 'Lakeme Makeup Kit',
        ratings: 4.7,
        price:220,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT5FtRQQ91AAok8svTeJBAhbruxU_Yd8npksHDJ5jPiOZEOGd38rsW0Sx7EtvKW8XifG7RH0kHVcw0wkp61dl-D_AZ9_jnea4Un6Bn7JRk&usqp=CAE',
    },
    {
        id:10,
        category: 'Home & Living',
        productName: 'Modern Art Wall',
        ratings: 4.7,
        price:78,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRBbiD2czashZ8Ack9iqYIs_PvxbO_CvCtp-HPNhbtFjuwpnDbckSEQECK9GsEWkT0ZnLKpKTCt-8qurCM8v5IBq16E8Qq7jNuGi9wL0i0&usqp=CAE',
    },
    {
        id:11,
        category: 'Men',
        productName: 'Slim fit Trousers',
        ratings: 4.5,
        price:150,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR0FvVJBGMT6QtyrZrSL8P0yULFrS4hxZRXSSwYTp2hu8lYBwSkazks5DYze90C8mO5-z-H5QrPAxE8lFl6ZMPtm9OFR54lnjcQ_F7t9VTl2J0kJxaf25Qxrw&usqp=CAE',
    },
    {
        id:12,
        category: 'Women',
        productName: 'Shrugs',
        ratings: 4.8,
        price:220,
        discountPrice: 59.99,
        imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRw67u-7f183I-pKCp84EXWm9iFyBbPSJY6VFRBlBknUjA4OOv69eBMKGjycF7KEKdkXl_Z4WXtrggCfkfPGYFHSXzOoC_FOKN2HxFsrufYnR9gaOyEtmSx&usqp=CAE',
    },
    {
        id:13,
        category: 'Beauty',
        productName: 'Liquid Blush Dark',
        ratings: 4.7,
        price:120,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRakTIG7u4MLZc8DNi-5LeUUa24hXCYYBk_CwbnX8wrYpDzdn5oPUu8KaFzEJQMtCA1BmyT-U5ABFuTj04mCHk1rjUTpfvG7sagi8yGA9c&usqp=CAE',
    },
    {
        id:14,
        category: 'Home & Living',
        productName: 'Family statue',
        ratings: 4.7,
        price:320,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSNogYBaiZSk2S379I96QpUoCnPtKGHMP1BqTFqiS-ndEUMqQKhXiHvYzIKMDUtVFW5XWcVwQRgUIRUHzrdXXe7xDJoBwGub7ApgBYM6BA1&usqp=CAE',
    },
    {
        id:15,
        category: 'Men',
        productName: 'Kurta Pyjama',
        ratings: 4.7,
        price:350,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRMJb3jSyyh2Ma_cdy7uMocE4lOVLFOABRz31mRhqwNmdSH-yf8SYNhSA07-ukUHZU-XUua817qBrELC3-bAd4cnrwoBtvNofx6qt4fl70FkhZ5mLnKqSM8Hw&usqp=CAE',
    },
    {
        id:16,
        category: 'Women',
        productName: 'Floral Print Top',
        ratings: 4.8,
        price:220,
        discountPrice: 59.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQvcfG4yWpLg_rwz7PKhhZMNjZAeOpVwr2gPB-HfXZkrG4x7Hpgtn2TFGV_AOrLccWlZMMgrp-7DCLS3W8V50RVaulekYBMWQXshf8eYJGI&usqp=CAE',
    },
    {
        id:17,
        category: 'Home & Living',
        productName: 'Art home decoration',
        ratings: 4.7,
        price:300,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQQhOgSmC4PbWlh60_rW11yo1UuXv7VQBOK5QwAbFAvuXqhCiaB-wjXvWzRVZQEBXncJibSMDOeqTPcIuPREvLZL6KgBWOrT6yotyI0PWY&usqp=CAE',
    },
    {
        id:18,
        category: 'Men',
        productName: 'Track pants',
        ratings: 4.7,
        price:400,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQCgyHFdtUmQT19il7Iyn_IHjFS5NL21BSazMdbZDhJVFf5SVtfiUj02KmSoY3erDWNveoU0Tr13TacJMQRyZZ8MpOULJcMrBc4LgjzmQA&usqp=CAE',
    },
    {
        id:19,
        category: 'Home & Living',
        productName: 'Wodden Wall Hanging',
        ratings: 4.7,
        price:370,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSEo-k2SfUCIRliItOydHDfTZvCdF6VXiNtdbrx_Jc4QsDn87Smbs0P1KFQ3eDzTxLEuNwayHduPK-jIdJaKPtSGsuS200COwQ1AClimKQsyudgICRRkLk9xA&usqp=CAE',
    },
    {
        id:20,
        category: 'Beauty',
        productName: 'Skin care Kit',
        ratings: 4.7,
        price:500,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTfoQp2BrjV2iTP2mBGFZKHy_Yl0XIYDzSyLqGu4S7T7zdRM4XJ2vak6Hs2ptwpGgrTgUdiafMKr1-IJKsNe6z070B_Rm7kJaNNxuXnU1YijM31MCEz_M-XGQ&usqp=CAE',
    },
    {
        id:21,
        category: 'Kids',
        productName: 'T-shirts',
        ratings: 4.7,
        price:250,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSeyBJ0krh5-eg7jCFccZsvmuQLj7dKTKadsw4Y_ytRqzg-EyTNFcTx6HpuzFXsdSSSNhuQWs85gLkwnHYbWvuPA1NGwJG_9MqMztsiNB2t&usqp=CAE',
    },
    {
        id:22,
        category: 'Men',
        productName: 'Track Suits',
        ratings: 4.7,
        price:350,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS9VOYCMoSFUec09eckd70POVceW9DXjdHfZCldjSSSVJBP_-EP6pZQnFH6D2N1EMMaSSSYnTtNnmeKvIgzZhiJZmi2Rw6Yx0tQyc4UC6wGaUXU-DFTTgr7&usqp=CAE',
    },

    {
        id:23,
        category: 'Women',
        productName: 'Kurta Set',
        ratings: 4.8,
        price:400,
        discountPrice: 59.99,
        imageUrl: 'https://www.libas.in/cdn/shop/files/6_b1d6cbbe-ac68-450c-af2b-1c24479d26a7.jpg?v=1715755774',
    },
    {
        id:24,
        category: 'Home & Living',
        productName: 'Enchanted Artistry home decor',
        ratings: 4.7,
        price:350,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQE0CJXnV9ETP0MaJzV6caJDn9nR-QzE6b-oQg89tGnurTKKzHspKwFl0N7TMxwtkpizJ1SBqg9bZD6qLIUII4UI9oRMQkyj3flpLUWIESO8I6X5MBupv8B&usqp=CAE',
    },
    {
        id:25,
        category: 'Beauty',
        productName: 'Melt HAir Mask',
        ratings: 4.7,
        price:330,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQPSoDdUL1GlsKyX-Vc1TQKCYSKR3BPH_QPTm6bdei6zX_w9_LuTRqDY96VBjlyVgWwOqdAo_0QMuxdmCPo1V5Pye1LkKP_Q3KP_B6AFLpKew7A1CfNhSDxYA&usqp=CAE',
    },
    {
        id:26,
        category: 'Men',
        productName: ' Jeans Pants',
        ratings: 4.7,
        price:500,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQf7e-mKJ-SpZbnvrcBnwISGVRK9cmp0xQ1WEiykstewqPIroS563DiWeW_OR-VyN-61anUoM5btZbkWGoO3aUYvtzgssXRgB4sECwtSh9m1nioPmIdJPrFEg&usqp=CAE',
    },
    // Add more men's outfits...

    // Women's Outfits
    {
        id:27,
        category: 'Kids',
        productName: 'Shorts',
        ratings: 4.7,
        price:200,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQEscuwHpGBvcM12fcwQPDJNfmE9FRPukEj_RkxKaOYzNG22afZ0uJeQqT5YPZPGoJk0_NxUA8eoBVM-hIwAdEBplWIfsFRniRuF09hXgqqHG1yjjJG6zVbHg&usqp=CAE',
    },
    {
        id:28,
        category: 'Home & Living',
        productName: 'Aaaradyat Show piece',
        ratings: 4.7,
        price:300,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTkIcl1ltQdj0_3M3qpv1xliKXkMvLwM9VMRaNUsc8ZYrldQttdlhCnBnJzYSuxJRrL-bgTR1W565qqH2CgMFQlja88Qg3VPK_QouSc1v6Z&usqp=CAE',
    },
    {
        id:29,
        category: 'Men',
        productName: 'Shorts',
        ratings: 4.7,
        price:350,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcStkfuo-L_f0prnzwQQmeCfx7FVbfoouy5TN3muDt3I_zgDPLb_OH6a0HEfEcKXio2FtPNDWT0y5z-llXYIwPavagkbJW8ljiyWMTnOo2PJdVhX6FlMXyi3Dg&usqp=CAE',
    },
    {
        id:30,
        category: 'Beauty',
        productName: 'Pigmentation Skincare Kit',
        ratings: 4.7,
        price:550,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ_wbC0LivkNRUhbxcamzOdO1_cl3KfIDy1-bf0oYbOblPEc-QTaInE8Y2gnOGqBJ_DbvSodZeisy3DjYbnEzell6fySvvJK7pO0w2gduU&usqp=CAE',
    },
    {
        id:31,
        category: 'Women',
        productName: 'Sarees',
        ratings: 4.8,
        price:800,
        discountPrice: 59.99,
        imageUrl: 'https://www.libas.in/cdn/shop/files/1_0a2f42af-575f-4ac6-ae61-810885b8d57a.jpg?v=1717571668',
    },
    {
        id:32,
        category: 'Home & Living',
        productName: 'Home sake lamp',
        ratings: 4.7,
        price:279,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSXu94IOsFEzTuJugJnlxOlAfoDKj8gWFkZIZHCg9YJD4DuCxf4pRSZOJBZpDBjKdyJHYF4qf7FomRQqYeXs2YneTuzTsyrcaXMJzkH5fo&usqp=CAE',
    },
    {
        id:33,
        category: 'Men',
        productName: ' Jacket',
        ratings: 4.7,
        price:390,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS0uT4cf6q7JkNCOJnNNysRwtzfLCSqoYC88zGnr-STAmdveTqawIMO67hCm_nkVrp1RKMsPnQ-LJuxhP-B0IkHORY4bAP_UXotBcfhl3Oa&usqp=CAE',
    },
    {
        id:34,
        category: 'Kids',
        productName: 'Trousers',
        ratings: 4.7,
        price:430,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTGxXTpVhMBkXdHoL_5gxkIlZfgjRVfq3EUV6JE_y2-M6qd6WP8OzR4NLOGycDlG0qZCyD6hfC-_YZ8rDHjS2J42x0amVBBWwddnSy4axbY&usqp=CAE',
    },
    {
        id:35,
        category: 'Home & Living',
        productName: 'Swan Pair show piece',
        ratings: 4.7,
        price:250,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSWJ7e6wizfEXmYYYRospeFQZdxL8QvIYFy9UElH97ral36ccSsM0KtcOkNAITTSIsv6J7hwAwozMWpXWuqqf59emhvqNspqROoFpRNe7s&usqp=CAE',
    },
    {
        id:36,
        category: 'Kids',
        productName: 'Skirts',
        ratings: 4.7,
        price:220,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQkzdZPU_GzLm-uFZ0xeYPV1G3nNWStVaRcrAxcIlaPz9-gr4-249O6IkLKp45UlxFsQ-IsOjl9FY1XcDdBvZxIr8BGR5mQ&usqp=CAY',
    },
    {
        id:37,
        category: 'Beauty',
        productName: 'Routine Clean Beauty KIt',
        ratings: 4.7,
        price:390,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSPD2Phr8KjCjv7P_w9dUZQWK_zeW8pduXsAuDr6TBjTstYVAsrojqAts-oB8HjQbse6GL2XpBoaJdv_yGupU_PlFoIfDapJAbgJsvuSUcS&usqp=CAE',
    },

    {
        id:38,
        category: 'Men',
        productName: 'Suits',
        ratings: 4.7,
        price:400,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSYfR8e0Yi1MNgvR-etzL7mPsHnUr_O9xQcW53Za0mJgu3rHYs4DipvgDqD811tBEos48BFCgiQ6YCg4fizubhNiuPzqissXce0wBVhhnR7&usqp=CAE',
    },
    {
        id:39,
        category: 'Women',
        productName: ' Dresses',
        ratings: 4.8,
        price:450,
        discountPrice: 59.99,
        imageUrl: 'https://www.libas.in/cdn/shop/files/1_01787e43-b2c4-455f-8b1d-76ec5bd8ee6f.jpg?v=1716361325',
    },
    {
        id:40,
        category: 'Kids',
        productName: 'Blouses',
        ratings: 4.7,
        price:200,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRQOrcoTZPYniO0c7OjO3Uk65efR9EcdZCCfEA4HSTS7yLAUcCgMkJfq0xNBCA83iUv4gDkwYPDz64piw1hlJETXZuVFAvMXxE8k3yrSG-8LyRppU2ZfY8eTw&usqp=CAE',
    },
    {
        id:41,
        category: 'Women',
        productName: 'Floral Maxi Dress',
        ratings: 4.7,
        price:430,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTZc4Mqrsua60mDjfsBvV6QBHcLT7DOuSGZDh_H-Y05bzjh6g_TCF1A3DWk2KnMhOSrFOSnL6DRQnUSz-HqdDeiyhMxKBMMLA6BAVRtda8rXpGDq2UzqonA&usqp=CAE',
    },
    {
        id:42,
        category: 'Beauty',
        productName: 'Hydrating Travel Kit',
        ratings: 4.7,
        price:470,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQKrIM0rmOM3IHDAGs5b8qG-haU0le6gSywfUhbBg507bC1Y1fPeXXNOJg2iVScWK46O4NK0e9nBj92kgkR45QA6fAU9JmsqF9Tnsv7blkU&usqp=CAE',
    },
    {
        id:43,
        category: 'Kids',
        productName: 'Striped Polo Shirt',
        ratings: 4.7,
        price:300,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQe1R5Jgth6LD3wO5fHWFOCUrIeGWVdjcVkK0fFt3BNy13gig2W8_yD_7q3GBAFbypeylhpHgFuMeSWJOHHBpyfIW3DBN-Y9_1UlQ3KD4UzSztBSeTR7Il5&usqp=CAE',
    },
    {
        id:44,
        category: 'Women',
        productName: 'Suits',
        ratings: 4.8,
        price:450,
        discountPrice: 59.99,
        imageUrl: 'https://www.libas.in/cdn/shop/files/33124O.jpg?v=1714548867',
    },
    {
        id:45,
        category: 'Beauty',
        productName: 'Botnal Men and Women Face wash',
        ratings: 4.7,
        price:600,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRdiNwWoLALAjL2EPp343vtSjyAxYk1wgUijHfP03fr2u0p6kj5HZk_dbg6b_zLrXY-t_QL_qtiDFoZoWqCsOF7uUTxaR4c_lcp9WZc-WQufleyAqlej4hikQ&usqp=CAE',
    },

    {
        id:46,
        category: 'Women',
        productName: 'Skirt Top',
        ratings: 4.8,
        price:380,
        discountPrice: 59.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSxlGd7MuroVWzYuAoDooaRlr_4PDgnSIDtzgyxBQa_f2bynZ9aOH7TZoV0xM7JCV8qchz7tcCrvUJYGISPGpjwHuXKMWkbhGTa8hXaCGzIZ6RPu2tszNt9Hg&usqp=CAE',
    },
    {
        id:47,
        category: 'Beauty',
        productName: 'Mamaearth Set',
        ratings: 4.7,
        price:600,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTquVkvSBNGCdg5-1b15MZHcKVBOwM4ATsb4i2IVEGmH46sKuBCW5-HqYJ819EBnEFW2kruPcq1VYdeV2AQk368xY9h64D3zSN5ApXSADT9ODEcxpee9RjWjQ&usqp=CAE',
    },
    {
        id:48,
        category: 'Kids',
        productName: 'Gowns',
        ratings: 4.7,
        price:190,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRAyi89NLZ5Lx-o1urOHktMxABxQMo7r3iAtAGpAIuTqTIq__tfBAuazg0D5IYGa0TLvL-st6uWsExuIE_-vdqZnMe8ilIboMMDt-RZA98_&usqp=CAE',
    },
    // Add more women's outfits...

    // Kids' Outfits
    {
        id:49,
        category: 'Kids',
        productName: 'Cartoon Print Tee',
        ratings: 4.6,
        price:200,
        discountPrice: 14.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSlThfZs6zBsBzA3PvfFma-lhzVLoXC52Z8mQU8C9cz0iP-UT-eKqB3Pcx2VYUifYxsEsYEVDRh2FCMOfLvzR6RWQWunqB9LgoTAMEWEQShQHAhLZ3YbnkI6Q&usqp=CAE',
    },
    {
        id:50,
        category: 'Women',
        productName: 'Trousers',
        ratings: 4.8,
        price:370,
        discountPrice: 59.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRVwgG7e6ynUWWSeuUihZjxfYxc0GNRNbGIgZD_T_Un0PmRJpV9e395Es91ETFMIshMtII0IieOo-GkBlGjE3F82n-g5S3SPN08Adw_vacqezOocgc1gZkT&usqp=CAE',
    },
    {
        id:51,
        category: 'Beauty',
        productName: 'Deep Hydrating Facial',
        ratings: 4.7,
        price:550,
        discountPrice: 49.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQNVjq9MJetrgm3wkNzCVDkoZompMfCFXZgyE3I_-Kv4VVZTGViqGATvOWPJqLq0b84tU3ICT24S5x0_PMLPXcAyDTriSIjCmDI07zjP-5rxZDugN1DVkI&usqp=CAE',
    },
    {
        id:52,
        category: 'Kids',
        productName: 'Striped Polo Shirt',
        ratings: 4.7,
        price:280,
        discountPrice: 19.99,
        imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQe1R5Jgth6LD3wO5fHWFOCUrIeGWVdjcVkK0fFt3BNy13gig2W8_yD_7q3GBAFbypeylhpHgFuMeSWJOHHBpyfIW3DBN-Y9_1UlQ3KD4UzSztBSeTR7Il5&usqp=CAE',
    },

    // Add more kids' outfits...
];

export default outfits;
